### ISSUE TITLE
component-lazyload的DEMO报错

### ISSUE THREAD

**Issue by LindaWhite** [quickappcn/hap-toolkit-usage#26]
![image](https://user-images.githubusercontent.com/12180536/89143346-e0a82b80-d57c-11ea-8dbf-0fc9c861c6b3.png)
打包报错，如图所示

**Comment by diydyq** [comment]
我这边运行是正常的，用的官网1070版本以及hap-toolkit@0.7.3；
能够正常打开页面呀；

**Comment by LindaWhite** [comment]
我的hap-toolkit@0.6.15   minPlatformVersion1040

**Comment by diydyq** [comment]
更新到对应版本就好了；
